- name: Switch to StackOverflow dataset
  # hosts: all
  hosts: hipri

  tasks:
    - name: Deactivate imdb
      command: sudo -u postgres psql -c "ALTER DATABASE imdb WITH ALLOW_CONNECTIONS false"
    - name: Terminate all connections to imdb
      command: sudo -u postgres psql -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'imdb' AND pid <> pg_backend_pid();"
    - name: Activate stackoverflow
      command: sudo -u postgres psql -c "ALTER DATABASE so WITH ALLOW_CONNECTIONS true"
    - name: ANALYZE stackoverflow
      command: sudo -u postgres psql so -c "ANALYZE"
