- name: Cancel current queries
  hosts: hipri

  tasks:
    - name: Cancel queries
      ansible.builtin.shell:
        cmd: sudo -u postgres psql -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND (datname = 'imdb' OR datname = 'so_future' OR datname = 'so_past');"
