CREATE INDEX IF NOT EXISTS date_dim_d_date_sk_idx ON date_dim (d_date_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_ticket_number_idx ON store_sales (ss_ticket_number);
CREATE INDEX IF NOT EXISTS store_sales_ss_item_sk_idx ON store_sales (ss_item_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_store_sk_idx ON store_sales (ss_store_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_cdemo_sk_idx ON store_sales (ss_cdemo_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_sold_date_sk_idx ON store_sales (ss_sold_date_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_customer_sk_idx ON store_sales (ss_customer_sk);
CREATE INDEX IF NOT EXISTS call_center_cc_call_center_sk_idx ON call_center (cc_call_center_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_bill_customer_sk_idx ON catalog_sales (cs_bill_customer_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_ship_date_sk_idx ON catalog_sales (cs_ship_date_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_warehouse_sk_idx ON catalog_sales (cs_warehouse_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_sold_date_sk_idx ON catalog_sales (cs_sold_date_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_call_center_sk_idx ON catalog_sales (cs_call_center_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_item_sk_idx ON catalog_sales (cs_item_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_ship_mode_sk_idx ON catalog_sales (cs_ship_mode_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_bill_cdemo_sk_idx ON catalog_sales (cs_bill_cdemo_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_bill_hdemo_sk_idx ON catalog_sales (cs_bill_hdemo_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_promo_sk_idx ON catalog_sales (cs_promo_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_order_number_idx ON catalog_sales (cs_order_number);
CREATE INDEX IF NOT EXISTS ship_mode_sm_ship_mode_sk_idx ON ship_mode (sm_ship_mode_sk);
CREATE INDEX IF NOT EXISTS warehouse_w_state_idx ON warehouse (w_state);
CREATE INDEX IF NOT EXISTS warehouse_w_warehouse_sk_idx ON warehouse (w_warehouse_sk);
CREATE INDEX IF NOT EXISTS web_sales_ws_order_number_idx ON web_sales (ws_order_number);
CREATE INDEX IF NOT EXISTS web_sales_ws_sold_date_sk_idx ON web_sales (ws_sold_date_sk);
CREATE INDEX IF NOT EXISTS web_sales_ws_warehouse_sk_idx ON web_sales (ws_warehouse_sk);
CREATE INDEX IF NOT EXISTS web_sales_ws_item_sk_idx ON web_sales (ws_item_sk);
CREATE INDEX IF NOT EXISTS web_sales_ws_bill_customer_sk_idx ON web_sales (ws_bill_customer_sk);
CREATE INDEX IF NOT EXISTS store_returns_sr_item_sk_idx ON store_returns (sr_item_sk);
CREATE INDEX IF NOT EXISTS store_returns_sr_returned_date_sk_idx ON store_returns (sr_returned_date_sk);
CREATE INDEX IF NOT EXISTS store_returns_sr_customer_sk_idx ON store_returns (sr_customer_sk);
CREATE INDEX IF NOT EXISTS store_returns_sr_cdemo_sk_idx ON store_returns (sr_cdemo_sk);
CREATE INDEX IF NOT EXISTS store_returns_sr_ticket_number_idx ON store_returns (sr_ticket_number);
CREATE INDEX IF NOT EXISTS item_i_item_sk_idx ON item (i_item_sk);
CREATE INDEX IF NOT EXISTS customer_c_current_addr_sk_idx ON customer (c_current_addr_sk);
CREATE INDEX IF NOT EXISTS customer_c_current_hdemo_sk_idx ON customer (c_current_hdemo_sk);
CREATE INDEX IF NOT EXISTS customer_c_customer_sk_idx ON customer (c_customer_sk);
CREATE INDEX IF NOT EXISTS customer_c_current_cdemo_sk_idx ON customer (c_current_cdemo_sk);
CREATE INDEX IF NOT EXISTS household_demographics_hd_demo_sk_idx ON household_demographics (hd_demo_sk);
CREATE INDEX IF NOT EXISTS household_demographics_hd_income_band_sk_idx ON household_demographics (hd_income_band_sk);
CREATE INDEX IF NOT EXISTS customer_address_ca_address_sk_idx ON customer_address (ca_address_sk);
CREATE INDEX IF NOT EXISTS store_s_store_sk_idx ON store (s_store_sk);
CREATE INDEX IF NOT EXISTS store_s_state_idx ON store (s_state);
CREATE INDEX IF NOT EXISTS customer_demographics_cd_demo_sk_idx ON customer_demographics (cd_demo_sk);
CREATE INDEX IF NOT EXISTS catalog_returns_cr_returning_customer_sk_idx ON catalog_returns (cr_returning_customer_sk);
CREATE INDEX IF NOT EXISTS catalog_returns_cr_returned_date_sk_idx ON catalog_returns (cr_returned_date_sk);
CREATE INDEX IF NOT EXISTS catalog_returns_cr_item_sk_idx ON catalog_returns (cr_item_sk);
CREATE INDEX IF NOT EXISTS catalog_returns_cr_order_number_idx ON catalog_returns (cr_order_number);
CREATE INDEX IF NOT EXISTS reason_r_reason_sk_idx ON reason (r_reason_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_refunded_addr_sk_idx ON web_returns (wr_refunded_addr_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_returning_cdemo_sk_idx ON web_returns (wr_returning_cdemo_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_reason_sk_idx ON web_returns (wr_reason_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_item_sk_idx ON web_returns (wr_item_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_order_number_idx ON web_returns (wr_order_number);
CREATE INDEX IF NOT EXISTS web_returns_wr_refunded_cdemo_sk_idx ON web_returns (wr_refunded_cdemo_sk);
CREATE INDEX IF NOT EXISTS inventory_inv_item_sk_idx ON inventory (inv_item_sk);
CREATE INDEX IF NOT EXISTS inventory_inv_date_sk_idx ON inventory (inv_date_sk);
CREATE INDEX IF NOT EXISTS inventory_inv_warehouse_sk_idx ON inventory (inv_warehouse_sk);
CREATE INDEX IF NOT EXISTS income_band_ib_income_band_sk_idx ON income_band (ib_income_band_sk);
CREATE INDEX IF NOT EXISTS promotion_p_promo_sk_idx ON promotion (p_promo_sk);
CREATE INDEX IF NOT EXISTS store_sales_ss_item_sk_ss_sold_date_sk_idx ON store_sales (ss_item_sk, ss_sold_date_sk);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_bill_customer_sk_cs_item_sk_idx ON catalog_sales (cs_bill_customer_sk, cs_item_sk);
CREATE INDEX IF NOT EXISTS web_sales_ws_item_sk_ws_order_number_idx ON web_sales (ws_item_sk, ws_order_number);
CREATE INDEX IF NOT EXISTS store_returns_sr_customer_sk_sr_item_sk_idx ON store_returns (sr_customer_sk, sr_item_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_refunded_cdemo_sk_wr_returning_cdemo_sk_idx ON web_returns (wr_refunded_cdemo_sk, wr_returning_cdemo_sk);
CREATE INDEX IF NOT EXISTS web_returns_wr_item_sk_wr_order_number_idx ON web_returns (wr_item_sk, wr_order_number);
CREATE INDEX IF NOT EXISTS inventory_inv_date_sk_inv_item_sk_idx ON inventory (inv_date_sk, inv_item_sk);
CREATE INDEX IF NOT EXISTS catalog_returns_cr_item_sk_cr_order_number_idx ON catalog_returns (cr_item_sk, cr_order_number);
CREATE INDEX IF NOT EXISTS catalog_sales_cs_item_sk_cs_order_number_idx ON catalog_sales (cs_item_sk, cs_order_number);
CREATE INDEX IF NOT EXISTS store_sales_ss_customer_sk_ss_item_sk_ss_ticket_number_idx ON store_sales (ss_customer_sk, ss_item_sk, ss_ticket_number);
CREATE INDEX IF NOT EXISTS store_returns_sr_customer_sk_sr_item_sk_sr_ticket_number_idx ON store_returns (sr_customer_sk, sr_item_sk, sr_ticket_number);
